services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 2s
      retries: 5

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user_service:
    build:
      context: .
      dockerfile: Dockerfile.user_service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    # DEBUG:
    # volumes:
    #   - ./user_service.py:/app/user_service.py
    #   - ./requirements.txt:/app/requirements.txt

  goal_service:
    build:
      context: .
      dockerfile: Dockerfile.goal_service
    environment:
      - MONGO_URL=mongodb://mongo:27017
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    # DEBUG:
    # volumes:
    #   - ./goal_service.py:/app/goal_service.py
    #   - ./requirements.txt:/app/requirements.txt

volumes:
  postgres_data:
  mongo_data:
